"""Silver stage artifact models (#46).

refined result of Bronze raw records as a DuckDB table (#869), and schema/statistics/
preview/validation information together. The table is a ``TableHandle`` — a table in the
source's DuckDB connection with each column's Builder dtype; the connection itself is
not part of the model. Stages not yet on DuckDB read it through
``tabular.polars_bridge.to_polars``.

main components:
    - ValidationProblem: individual validation violations (structured objects, #261)
    - ValidationResult: schema validation result
    - SilverDataset: Silver stage artifact
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from ...tabular import PreviewSlice, SchemaInfo, TableStatistics
from ...tabular.duckdb_load import TableHandle

if TYPE_CHECKING:
    from .validate import ValidationProblem


@dataclass(frozen=True)
class ValidationResult:
    """Silver schema validation result."""

    ok: bool
    problems: tuple[ValidationProblem, ...] = ()


@dataclass(frozen=True)
class SilverDataset:
    """refined table and metadata generated by Silver stage."""

    table: TableHandle
    schema: SchemaInfo
    statistics: TableStatistics
    preview: PreviewSlice
    validation: ValidationResult
    source_bronze: str
    metadata: dict[str, str] = field(default_factory=dict)

    def close(self) -> None:
        """Close the table: its private connection, if it opened one (#869)."""
        self.table.close()

    def __enter__(self) -> SilverDataset:
        return self

    def __exit__(self, *_exc: object) -> None:
        self.close()
